### ISSUE TITLE
salt-rsp-formula

### ISSUE THREAD

**Issue by mrtsniper** [whytewolf/salt-debug#2]
Hi Thomas.

sorry this is not an issue. but i don't found another way to leave a message for you.
I'm searching for one of your git project : https://github.com/whytewolf/salt-rsp-formula that is no more existing on github.

I'm new saltstack user and want to use it for applying security patchs on and infrastructure containing windows and redhat servers

could you please re share this project so i can take it as example ?

PS: if needed you can email me : mrtsniper@gmail.com

Thanks and regards
Ridha.

**Comment by whytewolf** [comment]
sorry i completely nuked that code. out of all of my repos.
